name: xinai_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pyspark=3.1.2
  - pytorch=1.9.0
  - torchvision
  - cudatoolkit=11.1
  - pip:
    - mlflow==1.20.2
    - horovod==0.22.1
    - captum==0.4.0
    - transformers==4.11.3
    - pandas==1.3.3
    - numpy==1.21.2
    - scikit-learn==0.24.2
    - matplotlib==3.4.3
    - seaborn==0.11.2
    - jupyter==1.0.0
